
  # base de données de l'application
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - "3307:3307"
  #   environment:
  #     MYSQL_DATABASE: alayde
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   networks:
  #     - appinternals


  # backend de l'application

  # back:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: root
  #   networks:
  #     - appinternals

version: '3'

networks:
  my_network:
    driver: bridge

services:
  client:
    build: ./frontend
    command: sh -c "npm run build && npm start"
    environment:
      - NODE_ENV=production
    volumes:
      - web-client-build:/app/build
    networks:
      - my_network
    ports:
      - "4200:4200" 
  nginx:
    image: nginx:1.21.3
    depends_on:
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
    networks:
      - my_network

volumes:
  web-client-build:










