version: '3'

services:
  backend:
    image: djosh35/alayde-back:dockerisation
    expose:
      - 8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alayde
      - SPRING_DATASOURCE_USERNAME=alayde_wcs_user
      - SPRING_DATASOURCE_PASSWORD=alayde_wcs_password

  frontend:
    image: djosh35/alayde-front:dockerisation
    ports:
      - 8000:80
    environment:
    #NOTHING FOR NOW

  nginx:
    image: nginx:1.21.3
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build:
