version: '3'

services:
  backend:
    build: 
      context: ./backend  # Répertoire où se trouvent les fichiers Dockerfile pour le backend
    expose:
      - 8080
    environment:
      - APPLI_ENV=developpement
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alayde
      - SPRING_DATASOURCE_USERNAME=alayde_wcs_user
      - SPRING_DATASOURCE_PASSWORD=alayde_wcs_password

  frontend:
    build:
      context: ./frontend  # Répertoire où se trouvent les fichiers Dockerfile pour le frontend
    ports:
      - 8000:80
    environment:
      - APPLI_ENV=developpement

  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build: 
