version: "3"

services:
  db:
    container_name: app_prod_db
    image: mysql:8.0
    restart: always
    ports:
      - "5000:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - appinternals

  back:
    container_name: app_prod_back
    ports:
      - "8080:8080"
    image: ${DOCKER_USER}/alayde-back:${DOCKER_IMAGE_TAG}
    restart: always
    depends_on:
      - db
    networks:
      appinternals:
        aliases:
          - back
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  nginx:
    container_name: app_prod_front
    image: ${DOCKER_USER}/alayde-front:${DOCKER_IMAGE_TAG}
    depends_on:
      - back
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    networks:
      - appinternals

volumes:
  db:
    driver: local

networks:
  appinternals:
    name: appinternals_app_prod
