version: '3'

services:
  nginx:
    image: nginx:1.21.3
    depends_on:
      - client
      - back
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

  client:
    build: ./frontend
    restart: always
    volumes:
      - web-client-build:/app/build
    ports:
      - "4200:80"

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "5000:3306"  # Modifier le port pour correspondre au port MySQL par défaut
    env_file:
      - .env

  back:
    build:
      context: ./backend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/alayde  # Utilisation du service "db" et du port MySQL par défaut
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  web-client-build:
