version: '3'

services:
  backend:
    image: djosh35/alayde-back:dockerisation
    command: sh -c "mvn clean install && java -jar target/alayde-0.0.1-SNAPSHOT.jar"
    expose:
      - 8080
    environment:
      - APPLI_ENV=production
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/alayde
      - SPRING_DATASOURCE_USERNAME=alayde_wcs_user
      - SPRING_DATASOURCE_PASSWORD=alayde_wcs_password

  frontend:
    image: djosh35/alayde-front:dockerisation
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - APPLI_ENV=production 
  nginx:
    image: nginx:1.21.3
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8010}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build:
