name: Alayde backend CI

on:
  push:
    paths:
      - 'back/**'  # Déclenche uniquement lorsque des changements sont effectués dans le dossier 'back'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend with Maven
        run: mvn --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend
        run: |
          docker push djosh35/docker-back:${GITHUB_REF##*/}