name: Alayde frontend CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Utilise la version appropriée

      - name: Install dependencies
        run: npm install

      - name: Build Frontend with Angular
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Frontend
        run: |
          docker build -t djosh35/docker-front:${GITHUB_REF##*/} .
          docker push djosh35/docker-front:${GITHUB_REF##*/}
