name: Alayde frontend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0" # Utilisez la version de Node.js appropriée

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run Jest Tests
        run: |
          cd frontend
          npm test

      # Run Cypress Tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t djosh35/alayde-front:${GITHUB_REF##*/} .
          docker push djosh35/alayde-front:${GITHUB_REF##*/}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and Push Backend Docker Image
        working-directory: ./backend
        run: ./mvnw --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/} "-Dimage.dockeruser=${{ secrets.DOCKERHUB_USERNAME }}/"

      - name: Run Backend Tests
        working-directory: ./backend
        run: ./mvnw test

      - name: Display local images
        run: docker images

      - name: Push Backend Docker Image
        run: docker push djosh35/alayde-back:${GITHUB_REF##*/}
