name: Alayde backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend with Maven
        run: |
          cd backend
          chmod +x mvnw
          ./mvnw clean install

      - name: Build Docker image
        run: docker build -t djosh35/alayde-back:${GITHUB_REF##*/} backend

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend
        run: docker push djosh35/alayde-back:${GITHUB_REF##*/}
