name: Alayde frontend CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'  # Utilise la version appropriée

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Frontend
        run: |
          cd frontend  # Change the working directory to 'frontend'
          docker build -t djosh35/alayde-front:${GITHUB_REF##*/} .
          docker push djosh35/alayde-front:${GITHUB_REF##*/} 

          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # build backend image with Spring Boot plugin for Maven 
      - name: Build BACK image with Maven
        working-directory: ./backend
        run: ./mvnw --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/} "-Dimage.dockeruser=${{ secrets.DOCKERHUB_USERNAME }}/"      

      - name: Login to DockerHub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

                  # print generated images
      - name: Display local images
        run: docker images

      - name: Push Backend
        run: docker push djosh35/alayde-back-img:${GITHUB_REF##*/}


